apiVersion: v1
kind: Service
metadata:
  name: demo-angular-app
  namespace: ns-kuruvsaadm-system
  labels:
    run: demo-angular-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: demo-angular-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-angular-app
  namespace: ns-kuruvsaadm-system
  labels:
    run: demo-angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-angular-app
  template:
    metadata:
      labels:
        run: demo-angular-app
    spec:
      containers:
      - name: demo-angular-app
        image: saneeshnair/demo-angular-app
        ports:
        - containerPort: 80
        - containerPort: 443

